name: Application CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  pipeline-test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        continue-on-error: true
      - name: Run backend test
        run: |
          chmod +x gradlew
          ./gradlew clean test -i
      - name: Upload Test Html Report
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: HTML test report
          path: build/reports/tests/test





